[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
amqprs = "1.2.0"
tokio = { version = "1.27.0", features = ["rt-multi-thread", "macros"] }
prost = "0.11.9"
tonic = "0.9.1"
tokio-stream = "0.1"
serde_json = "1.0"

[build-dependencies]
tonic-build = "0.9.1"