version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
    - 5672:5672
    - 8081:15672
    environment:
    - RABBITMQ_DEFAULT_USER=user
    - RABBITMQ_DEFAULT_PASS=password